version: "3.9"
services:
  web:
    build: 
      context: .
      args:
          NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
          NEXT_PUBLIC_SOCKET_URL: ${NEXT_PUBLIC_SOCKET_URL}
    image: ${RELEASE_IMAGE_NAME}
    ports:
      - ${EXPOSE_PORT}:3000
    extra_hosts:
      - "${BACKEND_DOMAIN}:${BACKEND_DOMAIN_IP}"
    entrypoint: yarn start
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
